Repository Study-Class/pagina_web, pull requests merged in 2020-10, with the labels that each got.

#4 Create LICENSE
  LICENSE
Labels: good first issue, hacktoberfest, hacktoberfest-accept

#5 Revert "Create LICENSE"
  LICENSE
Labels: hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#7 Improved Readme.md with different strcuture and desing. Also added in…
  CONTRIBUTING.md
  README.md
  codigo_de_conducta.md
  webpage.png
Labels: documentation, hacktoberfest-accepted
